Update clp-migrate-php-fpm-socket
Input error handling. Check if input from user is actually a number and that a site for that number was listed

diff --git a/tcp-tunnel-migration/clp-migrate-php-fpm-socket b/tcp-tunnel-migration/clp-migrate-php-fpm-socket
--- a/tcp-tunnel-migration/clp-migrate-php-fpm-socket
+++ b/tcp-tunnel-migration/clp-migrate-php-fpm-socket
@@ -29,9 +29,20 @@ if [ -z "$domain_number" ]; then
   exit 2
 fi
 
+# Check if the input is numeric
+if ! [[ $domain_number =~ ^[0-9]+$ ]]; then
+  echo "Invalid input. Enter only numbers to pick the site you want to migrate."
+  exit 3
+fi
+
 # Get the selected domain id and name
 site_id=$(echo "${domain_array[$((domain_number - 1))]}" | cut -d "|" -f 1)
 domain_name=$(echo "${domain_array[$((domain_number - 1))]}" | cut -d "|" -f 2)
+
+if [ -z "$domain_name" ]; then
+  echo "Selected site does not exist."
+  exit 4
+fi
 
 echo "----------------------------------------"
 echo "Starting migration of $domain_name"
